server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Fix for React Router: redirect all requests to index.html to avoid 404s
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional: Basic cache control for static assets
    location ~* \.(?:css|js|jpg|svg|png)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
